
language: c

before_install:
- curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
- chmod 755 pkg-build.sh
- ./pkg-build.sh bootstrap
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- export PATH="$PATH:$(./pkg-build.sh r_path)"

install:
- ./pkg-build.sh install_github hadley/lazyeval igraph/igraphdata gaborcsardi/roxygen
- ./pkg-build.sh install_r magrittr falsy roxygen2 NMF irlba
- git submodule update
- make
- ./pkg-build.sh install_deps
- ./pkg-build.sh install_bioc graph
- ./pkg-build.sh install_r rgl ape scales

script:
- ./pkg-build.sh run_build
- ./pkg-build.sh run_check

after_failure:
- ./pkg-build.sh dump_logs

after_success:
- tools/travis_deploy.sh igraph_*.tar.gz

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
  - RVERSION=3.1.2
  global:
    secure: GRGRLr+X8JZf32QiEJ0UxpT0RRe8uVJe8ipAW4IwrNv2G3PxifsJAcpGE3XtEmFT9RAYAbo/tt7f00INOUa4xqn9smzvoP/0i2SLw7FegA+eE2yuNI3GCAkQ+lzalLyvUmkmjhYKGhUKiYqLUQ8iNs/Pjgbpqde+V3ZvP6rX0CI=
